// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FootballDataAPI.Responses
{

    public partial class LeaguesMatchesResponse
    {
        public class Self2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class LeaguesMatchesResponse
    {
        public class Soccerseason2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class LeaguesMatchesResponse
    {
        public class Links0
        {

            [JsonProperty("self")]
            public Self2 Self;

            [JsonProperty("soccerseason")]
            public Soccerseason2 Soccerseason;
        }
    }

    public partial class LeaguesMatchesResponse
    {
        public class Self3
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class LeaguesMatchesResponse
    {
        public class Soccerseason3
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class LeaguesMatchesResponse
    {
        public class HomeTeam2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class LeaguesMatchesResponse
    {
        public class AwayTeam2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class LeaguesMatchesResponse
    {
        public class Links2
        {

            [JsonProperty("self")]
            public Self3 Self;

            [JsonProperty("soccerseason")]
            public Soccerseason3 Soccerseason;

            [JsonProperty("homeTeam")]
            public HomeTeam2 HomeTeam;

            [JsonProperty("awayTeam")]
            public AwayTeam2 AwayTeam;
        }
    }

    public partial class LeaguesMatchesResponse
    {
        public class Result2
        {

            [JsonProperty("goalsHomeTeam")]
            public int? GoalsHomeTeam;

            [JsonProperty("goalsAwayTeam")]
            public int? GoalsAwayTeam;
        }
    }

    public partial class LeaguesMatchesResponse
    {
        public class Fixture
        {

            [JsonProperty("_links")]
            public Links2 Links;

            [JsonProperty("date")]
            public string Date;

            [JsonProperty("status")]
            public string Status;

            [JsonProperty("matchday")]
            public int Matchday;

            [JsonProperty("homeTeamName")]
            public string HomeTeamName;

            [JsonProperty("awayTeamName")]
            public string AwayTeamName;

            [JsonProperty("result")]
            public Result2 Result;
        }
    }

    public partial class LeaguesMatchesResponse
    {

        [JsonProperty("_links")]
        public Links0 Links;

        [JsonProperty("count")]
        public int Count;

        [JsonProperty("fixtures")]
        public Fixture[] Fixtures;
    }

}
