// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FootballDataAPI.Responses
{

    public partial class LeaguesTeamsResponse
    {
        public class Link
        {

            [JsonProperty("self")]
            public string Self { get; set; }

            [JsonProperty("soccerseason")]
            public string Soccerseason { get; set; }
        }
    }

    public partial class LeaguesTeamsResponse
    {
        public class Self2
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class LeaguesTeamsResponse
    {
        public class Fixtures2
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class LeaguesTeamsResponse
    {
        public class Players2
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class LeaguesTeamsResponse
    {
        public class Links2
        {

            [JsonProperty("self")]
            public Self2 Self { get; set; }

            [JsonProperty("fixtures")]
            public Fixtures2 Fixtures { get; set; }

            [JsonProperty("players")]
            public Players2 Players { get; set; }
        }
    }

    public partial class LeaguesTeamsResponse
    {
        public class Team
        {

            [JsonProperty("_links")]
            public Links2 Links { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("code")]
            public string Code { get; set; }

            [JsonProperty("shortName")]
            public string ShortName { get; set; }

            [JsonProperty("squadMarketValue")]
            public string SquadMarketValue { get; set; }

            [JsonProperty("crestUrl")]
            public string CrestUrl { get; set; }
        }
    }

    public partial class LeaguesTeamsResponse
    {

        [JsonProperty("_links")]
        public Link[] Links { get; set; }

        [JsonProperty("count")]
        public int Count { get; set; }

        [JsonProperty("teams")]
        public Team[] Teams { get; set; }
    }

}
