// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FootballDataAPI.Responses
{

    public partial class LeaguesTeamsResponse
    {
        public class Self2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class LeaguesTeamsResponse
    {
        public class Soccerseason2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class LeaguesTeamsResponse
    {
        public class Links0
        {

            [JsonProperty("self")]
            public Self2 Self;

            [JsonProperty("soccerseason")]
            public Soccerseason2 Soccerseason;
        }
    }

    public partial class LeaguesTeamsResponse
    {
        public class Self3
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class LeaguesTeamsResponse
    {
        public class Fixtures2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class LeaguesTeamsResponse
    {
        public class Players2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class LeaguesTeamsResponse
    {
        public class Links2
        {

            [JsonProperty("self")]
            public Self3 Self;

            [JsonProperty("fixtures")]
            public Fixtures2 Fixtures;

            [JsonProperty("players")]
            public Players2 Players;
        }
    }

    public partial class LeaguesTeamsResponse
    {
        public class Team
        {

            [JsonProperty("_links")]
            public Links2 Links;

            [JsonProperty("name")]
            public string Name;

            [JsonProperty("code")]
            public string Code;

            [JsonProperty("shortName")]
            public string ShortName;

            [JsonProperty("squadMarketValue")]
            public string SquadMarketValue;

            [JsonProperty("crestUrl")]
            public string CrestUrl;
        }
    }

    public partial class LeaguesTeamsResponse
    {

        [JsonProperty("_links")]
        public Links0 Links;

        [JsonProperty("count")]
        public int Count;

        [JsonProperty("teams")]
        public Team[] Teams;
    }

}
