// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FootballDataAPI.Responses
{

    public partial class MatchResponse
    {
        public class Self2
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Soccerseason2
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class HomeTeam2
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class AwayTeam2
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Links5
        {

            [JsonProperty("self")]
            public Self2 Self { get; set; }

            [JsonProperty("soccerseason")]
            public Soccerseason2 Soccerseason { get; set; }

            [JsonProperty("homeTeam")]
            public HomeTeam2 HomeTeam { get; set; }

            [JsonProperty("awayTeam")]
            public AwayTeam2 AwayTeam { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Result2
        {

            [JsonProperty("goalsHomeTeam")]
            public int GoalsHomeTeam { get; set; }

            [JsonProperty("goalsAwayTeam")]
            public int GoalsAwayTeam { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Fixture2
        {

            [JsonProperty("_links")]
            public Links5 Links { get; set; }

            [JsonProperty("date")]
            public string Date { get; set; }

            [JsonProperty("status")]
            public string Status { get; set; }

            [JsonProperty("matchday")]
            public int Matchday { get; set; }

            [JsonProperty("homeTeamName")]
            public string HomeTeamName { get; set; }

            [JsonProperty("awayTeamName")]
            public string AwayTeamName { get; set; }

            [JsonProperty("result")]
            public Result2 Result { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Self3
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Soccerseason3
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class HomeTeam3
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class AwayTeam3
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Links2
        {

            [JsonProperty("self")]
            public Self3 Self { get; set; }

            [JsonProperty("soccerseason")]
            public Soccerseason3 Soccerseason { get; set; }

            [JsonProperty("homeTeam")]
            public HomeTeam3 HomeTeam { get; set; }

            [JsonProperty("awayTeam")]
            public AwayTeam3 AwayTeam { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Result3
        {

            [JsonProperty("goalsHomeTeam")]
            public int GoalsHomeTeam { get; set; }

            [JsonProperty("goalsAwayTeam")]
            public int GoalsAwayTeam { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class LastHomeWinHomeTeam2
        {

            [JsonProperty("_links")]
            public Links2 Links { get; set; }

            [JsonProperty("date")]
            public string Date { get; set; }

            [JsonProperty("status")]
            public string Status { get; set; }

            [JsonProperty("matchday")]
            public int Matchday { get; set; }

            [JsonProperty("homeTeamName")]
            public string HomeTeamName { get; set; }

            [JsonProperty("awayTeamName")]
            public string AwayTeamName { get; set; }

            [JsonProperty("result")]
            public Result3 Result { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Self4
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Soccerseason4
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class HomeTeam4
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class AwayTeam4
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Links3
        {

            [JsonProperty("self")]
            public Self4 Self { get; set; }

            [JsonProperty("soccerseason")]
            public Soccerseason4 Soccerseason { get; set; }

            [JsonProperty("homeTeam")]
            public HomeTeam4 HomeTeam { get; set; }

            [JsonProperty("awayTeam")]
            public AwayTeam4 AwayTeam { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Result4
        {

            [JsonProperty("goalsHomeTeam")]
            public int GoalsHomeTeam { get; set; }

            [JsonProperty("goalsAwayTeam")]
            public int GoalsAwayTeam { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class LastWinHomeTeam2
        {

            [JsonProperty("_links")]
            public Links3 Links { get; set; }

            [JsonProperty("date")]
            public string Date { get; set; }

            [JsonProperty("status")]
            public string Status { get; set; }

            [JsonProperty("matchday")]
            public int Matchday { get; set; }

            [JsonProperty("homeTeamName")]
            public string HomeTeamName { get; set; }

            [JsonProperty("awayTeamName")]
            public string AwayTeamName { get; set; }

            [JsonProperty("result")]
            public Result4 Result { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Self5
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Soccerseason5
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class HomeTeam5
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class AwayTeam5
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Links4
        {

            [JsonProperty("self")]
            public Self5 Self { get; set; }

            [JsonProperty("soccerseason")]
            public Soccerseason5 Soccerseason { get; set; }

            [JsonProperty("homeTeam")]
            public HomeTeam5 HomeTeam { get; set; }

            [JsonProperty("awayTeam")]
            public AwayTeam5 AwayTeam { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Result5
        {

            [JsonProperty("goalsHomeTeam")]
            public int GoalsHomeTeam { get; set; }

            [JsonProperty("goalsAwayTeam")]
            public int GoalsAwayTeam { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Fixture3
        {

            [JsonProperty("_links")]
            public Links4 Links { get; set; }

            [JsonProperty("date")]
            public string Date { get; set; }

            [JsonProperty("status")]
            public string Status { get; set; }

            [JsonProperty("matchday")]
            public int Matchday { get; set; }

            [JsonProperty("homeTeamName")]
            public string HomeTeamName { get; set; }

            [JsonProperty("awayTeamName")]
            public string AwayTeamName { get; set; }

            [JsonProperty("result")]
            public Result5 Result { get; set; }
        }
    }

    public partial class MatchResponse
    {
        public class Head2head2
        {

            [JsonProperty("count")]
            public int Count { get; set; }

            [JsonProperty("timeFrameStart")]
            public string TimeFrameStart { get; set; }

            [JsonProperty("timeFrameEnd")]
            public string TimeFrameEnd { get; set; }

            [JsonProperty("homeTeamWins")]
            public int HomeTeamWins { get; set; }

            [JsonProperty("awayTeamWins")]
            public int AwayTeamWins { get; set; }

            [JsonProperty("draws")]
            public int Draws { get; set; }

            [JsonProperty("lastHomeWinHomeTeam")]
            public LastHomeWinHomeTeam2 LastHomeWinHomeTeam { get; set; }

            [JsonProperty("lastWinHomeTeam")]
            public LastWinHomeTeam2 LastWinHomeTeam { get; set; }

            [JsonProperty("lastAwayWinAwayTeam")]
            public object LastAwayWinAwayTeam { get; set; }

            [JsonProperty("lastWinAwayTeam")]
            public object LastWinAwayTeam { get; set; }

            [JsonProperty("fixtures")]
            public Fixture3[] Fixtures { get; set; }
        }
    }

    public partial class MatchResponse
    {

        [JsonProperty("fixture")]
        public Fixture2 Fixture { get; set; }

        [JsonProperty("head2head")]
        public Head2head2 Head2head { get; set; }
    }

}
