// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FootballDataAPI.Responses
{

    public partial class TeamsPlayersResponse
    {
        public class Self
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class TeamsPlayersResponse
    {
        public class Team2
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class TeamsPlayersResponse
    {
        public class Links2
        {

            [JsonProperty("_self")]
            public Self Self { get; set; }

            [JsonProperty("team")]
            public Team2 Team { get; set; }
        }
    }

    public partial class TeamsPlayersResponse
    {
        public class Player
        {

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("position")]
            public string Position { get; set; }

            [JsonProperty("jerseyNumber", NullValueHandling = NullValueHandling.Ignore)]
            public int JerseyNumber { get; set; }

            [JsonProperty("dateOfBirth")]
            public string DateOfBirth { get; set; }

            [JsonProperty("nationality")]
            public string Nationality { get; set; }

            [JsonProperty("contractUntil")]
            public string ContractUntil { get; set; }

            [JsonProperty("marketValue")]
            public string MarketValue { get; set; }
        }
    }

    public partial class TeamsPlayersResponse
    {

        [JsonProperty("_links")]
        public Links2 Links { get; set; }

        [JsonProperty("count")]
        public int Count { get; set; }

        [JsonProperty("players")]
        public Player[] Players { get; set; }
    }

}
