// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FootballDataAPI.Responses
{

    public partial class TeamsMatchesResponse
    {
        public class Self
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class TeamsMatchesResponse
    {
        public class Team2
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class TeamsMatchesResponse
    {
        public class Links3
        {

            [JsonProperty("_self")]
            public Self Self { get; set; }

            [JsonProperty("team")]
            public Team2 Team { get; set; }
        }
    }

    public partial class TeamsMatchesResponse
    {
        public class Self2
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class TeamsMatchesResponse
    {
        public class Soccerseason2
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class TeamsMatchesResponse
    {
        public class HomeTeam2
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class TeamsMatchesResponse
    {
        public class AwayTeam2
        {

            [JsonProperty("href")]
            public string Href { get; set; }
        }
    }

    public partial class TeamsMatchesResponse
    {
        public class Links2
        {

            [JsonProperty("self")]
            public Self2 Self { get; set; }

            [JsonProperty("soccerseason")]
            public Soccerseason2 Soccerseason { get; set; }

            [JsonProperty("homeTeam")]
            public HomeTeam2 HomeTeam { get; set; }

            [JsonProperty("awayTeam")]
            public AwayTeam2 AwayTeam { get; set; }
        }
    }

    public partial class TeamsMatchesResponse
    {
        public class Result2
        {

            [JsonProperty("goalsHomeTeam")]
            public int? GoalsHomeTeam { get; set; }

            [JsonProperty("goalsAwayTeam")]
            public int? GoalsAwayTeam { get; set; }
        }
    }

    public partial class TeamsMatchesResponse
    {
        public class Fixture
        {

            [JsonProperty("_links")]
            public Links2 Links { get; set; }

            [JsonProperty("date")]
            public string Date { get; set; }

            [JsonProperty("status")]
            public string Status { get; set; }

            [JsonProperty("matchday")]
            public int Matchday { get; set; }

            [JsonProperty("homeTeamName")]
            public string HomeTeamName { get; set; }

            [JsonProperty("awayTeamName")]
            public string AwayTeamName { get; set; }

            [JsonProperty("result")]
            public Result2 Result { get; set; }
        }
    }

    public partial class TeamsMatchesResponse
    {

        [JsonProperty("_links")]
        public Links3 Links { get; set; }

        [JsonProperty("count")]
        public int Count { get; set; }

        [JsonProperty("fixtures")]
        public Fixture[] Fixtures { get; set; }
    }

}
